# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.3.0
CMD ["logstash"]
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
