# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.3.0
#CMD ["/bin/logstash -f /usr/share/logstash/pipeline/logstash.conf"]
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
